AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - './Gemfile'
    - './db/**/*'
    - './bin/**/*'
    - './config/**/*'
    - './vendor/**/*'

Documentation:
  Enabled: false

Layout/ClassStructure:
  Categories:
    module_inclusion:
      - extend
      - include
      - prepend
    association:
      - has_one
      - has_many
    attribute:
      - attr_accessor
      - attr_reader
      - attr_writer
    ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - public_methods
      - protected_methods
      - private_methods

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Metrics/BlockLength:
  Exclude:
    - './spec/**/*'

Metrics/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - './Gemfile'
    - './Rakefile'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: []
    '%i': '[]'
    '%I': '[]'
    '%w': '[]'
    '%W': '[]'
    '%r': '{}'